language: python
python:
  - "3.6"

install:
  - pip install .

script:
  - "echo 'TODO: add tests'"

before_deploy:
  - git describe --dirty --always > VERSION
  - echo "Version"
  - cat VERSION

deploy:
  provider: pypi
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
